### ISSUE TITLE
계정 도메인 관련 작업 중 의문사항 정리

### ISSUE THREAD

**Issue by yunut** [yunut/kotlin_practice#1]
1. 도메인 단위 구조에서 로그인, 로그아웃의 대한 로직과 구조는 account 패키지에 들어가는게 맞는지?
   -> Spring security를 적용하였을때, 해당 인터페이스 및 설정은 계정 도메인에 적용해야되는지??
   -> '계정' 에 대한 도메인의 범위를 어디까지 산정해야 할지

2. 논 블로킹 아키텍쳐에서 작업이 완료되었을 시, 예를들어 작업이 완료되었을 경우, 이에대한 성공 여부와 혹은 에러 발생시 에러 메시지는 어떻게 전달하는지
	-> 블로킹 아키텍쳐에선 프론트가 해당 리턴을 기다리는데 논 블로킹은 어떻게 처리되는지?

**Comment by sangholim** [comment]
@yunut 
1. 답변입니다
  - Spring Security 같은 경우는 패키지가 아니라 , 인증 및 권한 여부를 uri `ant-matcher` 로 정할수 있습니다.
  - account에 있는 회원 도메인 역할에 따라 `로그인` `로그아웃` 기능이 포함될지 결정됩니다.
    `로그인/로그아웃` 진행 절차가  정의가 먼저라 생각됩니다.
2.  제가 아는한에서 답변 드리겠습니다.
    client- server는 서로 응답받을떄까지 연결되어 있습니다. 
    하지만 이 연결은 blocking처럼 응답을 받을떄까지 network  IO를 유지하는건 아닙니다.
    non-blocking인 경우, client의 요청을 처리를 담당하는 event-queue로 전달합니다.
    처리가 끝나는 경우에만 연결되어있는 client에게로 결과를 전달해주는 방식을 사용하고 있습니다.
    이 과정에서는 로직에 대한 처리가 끝날떄까지 대기하지 않고, 다른 로직에게 작업권을 주기 떄문에
    blocking 처럼 응답이 올떄까지 다는 network-io가 대기하지 않는다는 장점을 가지고 있습니다.
