### ISSUE TITLE
KeyCloak 클라이언트, 사용자 권한 관련 문제

### ISSUE THREAD

**Issue by yunut** [yunut/kotlin_practice#18]
# 개요
keyCloak 계정에서 userManage 권한을 부여할수 없음
 - client 의 사용자 생성 후  manage-account Role을 부여해야 하나 불가능 해 admin client 회원 가입 시 admin 계정으로 요청하는 사항에 대한 이슈

# 시나리오
## 1. 기본적으로 존재하는 account 계정의 manage-account 권한이 필요 함.
<img width="848" alt="image" src="https://user-images.githubusercontent.com/47917032/203520312-d8a36cb6-51ba-4a0f-9dc8-8ce7aab39d4c.png">

## 2. admin 생성 후 Role 부여 시 기본적으로 존재하는 Role을 부여하지 못하고 생성한 Role만 부여 가능
<img width="836" alt="image" src="https://user-images.githubusercontent.com/47917032/203523204-15becfa2-e9fc-41b2-af49-6f6b40e8fa9e.png">
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/47917032/203523127-4003f548-1f8f-4b78-a79a-b77190ce5872.png">

# 이슈관련 레퍼런스
 - 아래 관련 레퍼런스로 해결 가능할것 같으나 확실치 않음
https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions

해당 이슈 내용에 대한 의견 부탁드립니다. 감사합니다.

**Comment by sangholim** [comment]
@yunut 
- keycloak-admin-client 사용 샘플 github 주소 공유 드립니다. 소스 보시고 적용해 보세용
- [ Assign client level role to user](https://gist.github.com/thomasdarimont/c4e739c5a319cf78a4cff3b87173a84b)

**Comment by yunut** [comment]
@sangholim 
해당 소스 확인하였으나, 현재 발생한 이슈는 사용자 계정을 만들때, keyCloak 인증 서버의 유저 생성 권한이있는 admin 계정이 필요합니다.


https://gist.github.com/thomasdarimont/c4e739c5a319cf78a4cff3b87173a84b?permalink_comment_id=3783748#gistcomment-3783748

위에 링크에 해당 방법에 대한 설명이 나와있으나... 20버전 사용 시 UI인터페이스도 다르고 user manage 권한 추가가 되지않는 문제가있습니다.

**Comment by sangholim** [comment]
아 이해했습니다
Client internal -service 에 role  추가가 필요 하겠네여
브랜치 소스 최신화 해주시면 확인후 가이드 드릴게여

**Comment by yunut** [comment]
넵 금일 내로 PR 드리겠습니다 감사합니다.
