### ISSUE TITLE
로그인 api 정의

### ISSUE THREAD

**Issue by yunut** [yunut/kotlin_practice#26]
# 1. 개요
 - 계정 도메인의 로그인 API 정의입니다.

# 2. UI 프로토타입 및 시나리오
 ## 2.1 프로토 타입
<img width="817" alt="image" src="https://user-images.githubusercontent.com/47917032/202127587-320e660f-b22f-4763-b0d4-7ee62c138591.png">

 ## 2.2 시나리오
 2.2.1 로그인 폼 화면에서 ID, PW 데이터 입력 ( 소셜 로그인은 추후 구현)
 2.2.2 서버 측에 데이터 전달
 2.2.3 keycloak 인증 
 2.2.4 Access Token 발급
 2.2.5 로그인 처리 및 메인 페이지 이동

# 2. API 정의
|Method|URL|content-type|description|
|------|---|---|---|
|POST|/account/signin|application/json|계정 정보를 보내면 로그인|

 ## request
```
{
   "email": "test@test.com",
   "password": "1234",
}
```

 ## response
 ### 로그인 완료
```
HTTP/1.1 200 OK
{
}
```

 ### 예외 사항
 #### 이메일이 존재하지 않는 경우
```
HTTP/1.1 401
{
  "message": "계정이 존재하지 않습니다."
}
```

 #### 비밀번호가 다른 경우
```
HTTP/1.1 401
{
  "message": "비밀번호가 일치하지 않습니다."
}
```

**Comment by sangholim** [comment]
@yunut 
- 로그인 API 따로 만들지 않습니다.
  - keycloak open-id token end-point 에 요청합니다.
- 에러 메시지가 필요한 경우, 이메일/비밀번호 필드를 구분 짓지 않고, 하나의 에러로 통합합니다. `메시지를 통한 위험도를 낮춤`
  - 예시) `이메일 또는 비밀번호가 올바르지 않습니다`

**Comment by yunut** [comment]
넵 로그인은 프론트에서 인증서버로 요청하는것으로 작업하며
에러메시지는 프론트에서 컨트롤하겠습니다.
