### ISSUE TITLE
회원가입 화면 및 프로토타입 및 시나리오 설계

### ISSUE THREAD

**Issue by yunut** [yunut/kotlin_practice#5]
# 1. 개요
 - 계정 도메인의 회원가입 화면 프로토타입 및 시나리오 설계입니다.

# 2. 설계 내용
## 2.1 회원가입 화면
<img width="874" alt="image" src="https://user-images.githubusercontent.com/47917032/202137037-3500d750-5d42-4302-a9f9-5bcd6bf9c1ef.png">

## 2.2 시나리오
 2.2.1 회원가입 폼 화면에서 name, email, pw 등 데이터 입력
 2.2.2 데이터 암호화 및 서버 측에 데이터 전달
 2.2.3 데이터 복호화 및 데이터 검증
 2.2.4 DB에 데이터 저장

## 2.3 api 명세
   2.3.1 schema
```
url: /account/signup
methods: /POST
content-type: application/json
```

  2.3.2 request
```
{
   name: "테스트",
   email: "test@test.com",
   pw: "1234(암호화)"
   pwCheck: "1234(암호화)"
}
```

  2.3.3 response
```
code: 200
{
  account: {
        name: "테스트",
        email: "test@test.com"
  },
  success: true
}
```

```
code: 404
{
  success: false,
  errMsg: "내용"
}
```

**Comment by sangholim** [comment]
@yunut 
## 리뷰
- 필드명에 약어는 쓰지 않는걸 권장합니다.
- 회원의 이메일은 유일 무이한 값이기 때문에, 그러므로 회원가입시에 사용중인지 확인이 필요합니다.
- 응답값 정의는 rest-api 준수해서 작성이 필요합니다.
- 404 는 HttpStatus 규약상 무언가 찾을수 없을떄 사용되기 때문에, 회원가입에 용도에 맞지 않습니다.
- 회원가입시 데이터가 생성되기 때문에 201 Created 를 쓰는게 맞는거 같습니다. 
   그리고 응답값이 필요한지 논의가 필요합니다.
## 에러 케이스
- 회원 계정이 사용중인 경우

**Comment by sangholim** [comment]
- [ ] issue 만들기
